server/hotdesk/models.py
"""Model (databate table) definitions."""
from . import db
import datetime


class Desk(db.Model):
    """Desk model."""

    __tablename__ = 'desks'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(6), unique=True)
    # One to many relationship to bookings
    bookings = db.relationship('Booking', backref='desk', lazy='dynamic')

    def is_booked(self):
        """Find if a desk is currently booked."""
        if any((booking.is_active() for booking in self.bookings)):
            return True
        else:
            return False

    def active_booking(self):
        """Return the active booking for this desk if there is one."""
        for booking in self.bookings:
            if booking.is_active():
                return booking

        return None


class Booking(db.Model):
    """Booking model."""

    __tablename__ = 'bookings'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), unique=False)
    from_when = db.Column(db.DateTime, unique=False)
    until_when = db.Column(db.DateTime, unique=False)
    desk_id = db.Column(db.Integer, db.ForeignKey('desks.id'))

    def is_active(self):
        """Find if a booking is currently active."""
        current_time = datetime.datetime.now()
        active = (
            current_time >= self.from_when and current_time < self.until_when
            )
        return active

    def overlap(self, other):
        """
        Test if two bookings overlap.

        :arg other: The booking to test against.
        :type other: :class:`Booking`

        :returns: `True` if the two bookings conflict, `False` otherwise.
        :rtype: bool
        """
        # If other begins after self beings, but also begins before self ends
        if self.from_when <= other.from_when:
            if other.from_when < self.until_when:
                return True

        # Vice versa
        if other.from_when <= self.from_when:
            if self.from_when < other.until_when:
                return True

        return False

server/hotdesk/main/forms.py
"""Main app forms."""
from ..models import Desk
from datetime import datetime, timedelta
from flask_wtf import FlaskForm
from wtforms import (StringField, SubmitField, DateField, DateTimeField,
                     SelectField)
from wtforms.validators import DataRequired


def current_date():
    """Return the current date."""
    return datetime.now().date()


def current_time():
    """Return the current time."""
    return datetime.now()


def next_hour():
    """Return the current time plus one hour."""
    return datetime.now() + timedelta(hours=1)


class BookingForm(FlaskForm):
    """Desk booking form."""

    name = StringField('Name', validators=[DataRequired()])
    desk = SelectField('Desk', coerce=int, validators=[DataRequired()])
    date = DateField('Date', default=current_date,
                     validators=[DataRequired()])
    from_when = DateTimeField('From when', format="%H:%M",
                              default=current_time,
                              validators=[DataRequired()])
    until_when = DateTimeField('Until when', format="%H:%M",
                               default=next_hour,
                               validators=[DataRequired()])
    submit = SubmitField('Submit')

    def __init__(self):
        """Construct a :class:`BookingForm`."""
        super().__init__()

        # Get desk names from table
        self.desk.choices = [(desk.id, desk.name) for desk in Desk.query.all()]

server/hotdesk/__init__.py
"""App module."""
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy
import os
import pathlib

bootstrap = Bootstrap()
db = SQLAlchemy()
migrate = Migrate(compare_type=True)


def create_app(test_config=None):
    """Create Flask App instance."""
    app = Flask(__name__)
    app.config.from_mapping(
        SECRET_KEY="uxh)9l8;{P-us_&h>@q{u",
        SQLALCHEMY_DATABASE_URI=(
            "sqlite:///" + os.path.join(app.instance_path, "data.sqlite")
            ),
        SQLALCHEMY_TRACK_MODIFICATIONS=False
        )

    pathlib.Path(app.instance_path).mkdir(parents=True, exist_ok=True)

    if test_config:
        app.config.update(test_config)
    else:
        app.config.from_envvar("FLASK_CONFIG", silent=True)

    bootstrap.init_app(app)
    db.init_app(app)
    migrate.init_app(app, db)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .api import api_blueprint
    app.register_blueprint(api_blueprint)

    from .models import Desk, Booking

    @app.shell_context_processor
    def make_shell_context():
        """Create context for the `flask shell` session."""
        return dict(db=db, Desk=Desk, Booking=Booking)

    return app

server/hotdesk/api/__init__.py
"""RESTful API subapp."""
from flask import Blueprint
from flask_restful import Api

api_blueprint = Blueprint("api", __name__)
api = Api(api_blueprint)

from . import resources  # noqa: E402

__all__ = ["api", "api_blueprint", "resources"]

server/hotdesk/main/__init__.py
"""Main subapp."""
from flask import Blueprint

main = Blueprint("main", __name__)

from . import views, forms, errors  # noqa: E402

__all__ = ["main", "views", "forms", "errors"]

server/hotdesk/main/views.py
"""Main app views."""
from . import main
from .forms import BookingForm
from .. import db
from ..models import Booking, Desk
from datetime import datetime
from flask import render_template, redirect, url_for, flash


@main.route('/')
def index():
    """Index route."""
    return render_template('index.html')


@main.route('/book', methods=['GET', 'POST'])
def book():
    """Desk booking route."""
    form = BookingForm()
    if form.validate_on_submit():
        # Determine the begining and end of the booking as datetime objects
        date = form.date.data
        from_when = datetime.combine(date, form.from_when.data.time())
        until_when = datetime.combine(date, form.until_when.data.time())

        # Create a Booking objet
        booking = Booking(
            name=form.name.data,
            desk_id=form.desk.data,
            from_when=from_when,
            until_when=until_when
            )
        # Ensure the booking does not overlap with existing bookings
        bookings = Booking.query.filter_by(desk_id=form.desk.data).all()
        if any((booking.overlap(other) for other in bookings)):
            flash("Your request overlaps with an existing booking.")
            return render_template('book.html', form=form)

        # Ensure the booking ends after it begins
        if booking.from_when > booking.until_when:
            flash("Your request ends after it begins.")
            return render_template('book.html', form=form)

        # Ensure the booking is not for zero time
        if booking.from_when == booking.until_when:
            flash("Your request is for zero time.")
            return render_template('book.html', form=form)

        db.session.add(booking)
        db.session.commit()
        flash('Your desk is booked!')
        return redirect(url_for('main.bookings'))
    return render_template('book.html', form=form)


@main.route('/bookings')
def bookings():
    """Route to show all bookings."""
    bookings = Booking.query.all()
    return render_template('bookings.html', bookings=bookings)


@main.route('/desks')
def desks():
    """Route to show all desks and their current status."""
    desks = Desk.query.all()
    return render_template('desks.html', desks=desks)

server/hotdesk/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}Hotdesk Booking{% endblock %}

{% block navbar %}
<nav class="navbar navbar-inverse">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('main.index') }}">Hotdesk Booking</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('main.book') }}">Book</a></li>
                <li><a href="{{ url_for('main.desks') }}">Desks</a></li>
                <li><a href="{{ url_for('main.bookings') }}">Bookings</a></li>
            </ul>
        </div>
    </div>
</nav>
{% endblock %}

{% block content %}
<div class="container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}
    {% block page_content %}{% endblock %}
</div>
{% endblock %}

server/hotdesk/templates/book.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}
<div class="page-header">
    <h1>Book a Desk</h1>
</div>

{{ wtf.quick_form(form) }}
{% endblock %}

server/hotdesk/templates/bookings.html
{% extends "base.html" %}

{% block page_content %}
<h1>Bookings</h1>

<table class="table table-hover">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Desk</th>
            <th scope="col">Name</th>
            <th scope="col">Date</th>
            <th scope="col">From</th>
            <th scope="col">Until</th>
            <th scope="col">Active</th>
        </tr>
    </thead>
    <tbody>
        {% for booking in bookings %}
        <tr>
            <th scope="row">{{ booking.id }}</th>
            <td>{{ booking.desk.name }}</td>
            <td>{{ booking.name }}</td>
            <td>{{ booking.from_when.strftime("%Y-%m-%d") }}</td>
            <td>{{ booking.from_when.strftime("%H:%M") }}</td>
            <td>{{ booking.until_when.strftime("%H:%M") }}</td>
            <td>{{ "Yes" if booking.is_active() else "No" }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

server/hotdesk/templates/desks.html
{% extends "base.html" %}

{% block page_content %}
<h1>Desks</h1>

<table class="table table-hover">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Status</th>
        </tr>
    </thead>
    <tbody>
        {% for desk in desks %}
        <tr>
            <th scope="row">{{ desk.id }}</th>
            <td>{{ desk.name }}</td>
            {% if desk.is_booked() %}
            <td>{{ "Booked until {}".format(desk.active_booking().until_when.strftime('%H:%M')) }}</td>
            {% else %}
            <td>Free</td>
            {% endif %}
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

server/hotdesk/templates/index.html
{% extends "base.html" %}

{% block page_content %}
<h2>Hello world!</h2>
{% endblock %}